trigger:
  branches:
    include:
      - main


pool:
  vmImage: ubuntu-latest

variables:
  - group: github-secrets 
  - name: GITHUB_REPO
    value: 'sfeich/dbt_adventure_works'
  - name: GITHUB_BRANCH
    value: 'main'
  - name: GITHUB_USER
    value: 'sfeich'
  - name: GITHUB_EMAIL
    value: 's.f.eichinger@gmail.com'
  
steps:
- checkout: self

- script: |
    git config --global user.email "$(GITHUB_EMAIL)"
    git config --global user.name "$(GITHUB_USER)"

    echo "Auto-update at $(date)" >> update-log.txt

    git add .

    # check if there is anything to commit
    if git diff --cached --quiet; then
      echo "No changes to commit"
    else 
      git commit -m "Automated commit from Azure DevOps"
      git push https://x-access-token:$(GITHUB_TOKEN)@github.com/$(GITHUB_REPO).git $(GITHUB_BRANCH)
    fi

  displayName: "Commit and push to GitHub"   

