trigger:
  branches:
    include:
      - main


pool:
  vmImage: ubuntu-latest


resources:
  repositories:
    - repository: dbt_adventure_works
      type: git
      name: dbt_adventure_works
      ref: refs/heads/main


variables:
  - group: github-secrets 
  - name: GITHUB_REPO
    value: 'sfeich/dbt_adventure_works'
  - name: GITHUB_BRANCH
    value: 'main'
  - name: GITHUB_USER
    value: 'sfeich'
  - name: GITHUB_EMAIL
    value: 's.f.eichinger@gmail.com'
  

jobs:
  - job: CommitAndPush
    steps:  
      - checkout: dbt_adventure_works
        displayName: "Checkout dbt_adventure_works repository"

      - script: |
          curl -H "Authorization: Bearer $(GITHUB_TOKEN)" https://api.github.com/user
        displayName: "Verify GitHub Authentication"

      - script: |
          git checkout main
          git remote set-url origin https://x-access-token:$(GITHUB_TOKEN)@github.com/$(GITHUB_REPO).git 
          git branch -vv                      
        displayName: "Set GitHub remote"

      - script: |
          git config --global user.email "$(GITHUB_EMAIL)"
          git config --global user.name "$(GITHUB_USER)"

          echo "Auto-update at $(date)" >> update-log.txt

          git add .
        displayName: "Update log and stage changes"

      - script: |
          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else 
            git commit -m "Automated commit from Azure DevOps"
            git push origin $(GITHUB_BRANCH)
          fi
        displayName: "Commit and push changes"


