
version: 2

models:
  - name: stg_customer
    description: "Staging view of customer, derived from AdventureWorks core table DimCustomer"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: stg_product_subcategory
    description: "Staging view of product subcategory, derived from AdventureWorks core table DimProductSubcategory"
    columns:
      - name: ProductSubcategoryKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: ProductCategoryKey
        description: "A foreign key to link to table DimProductSubcategory"
        data_tests:
          - not_null 
      - name: EnglishProductSubcategoryName
        description: "Describes product sub-category"
        data_tests:
          - not_null

