
version: 2

models:
  - name: stg_customer
    description: "Staging view of customer, derived from AdventureWorks core table DimCustomer"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: stg_product
    description: "Staging view of product, derived from AdventureWorks core table DimProduct"
    columns:
      - name: ProductKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: ProductAlternateKey
        description: "The alternate key for this table"
        data_tests:
          - not_null # only satsifies not nullness; alternate keys are not unique
      - name: FinishedGoodsFlag
        description: "Indicates whether a product is a finished good"
        data_tests:
          - accepted_values:
              values: [0, 1]
      

