
version: 2

models:
  - name: stg_customer
    description: "Staging view of customer, derived from AdventureWorks core table DimCustomer"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

