version: 2

sources:
  - name: sql-server-on-prem   # source system name
    database: "{{ var('database_name') }}"    # database referenced by dbt commands
    schema: "{{ var('schema_name') }}"        # schema containing the source tables
    tables:       # table names as in the database
      - name: DimCustomer 
      - name: DimProductCategory  
      - name: DimProductSubcategory
      - name: DimProduct
      - name: DimDate 
      - name: FactInternetSales
      - name: FactInternetSalesReason
      - name: DimSalesReason