version: 2

sources:
  - name: sql-server-on-prem   # source system name
    database: AdventureWorksDW2022   
    schema: dbo   # schema containing the source tables
    tables:       # table names as in the database
      - name: DimCustomer 
      - name: DimProductCategory  
      - name: DimProductSubcategory
      - name: DimProduct
      - name: DimDate 
      - name: FactInternetSales
      - name: FactInternetSalesReason