
version: 2

models:
  - name: int_customer
    description: "Intermediate view of customer, derived from stg_customer view"
    columns:
      - name: CustomerKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: CustomerAlternateKey
        description: "The alternate key for this table"
        data_tests:
          - unique
          - not_null
      - name: GeographyKey
        description: "Foreign key to link to primary key of DimGeography table"
        data_tests:
          - not_null
      - name: FirstName
        description: "First name of the customer"      
      - name: MiddleName
        description: "Middle name of the customer"       
      - name: LastName
        description: "Last name of the customer"       
      - name: BirthDate
        description: "Date of birth of customer (in format yyyy/mm/dd)"
      - name: Age
        description: "Age of the customer"
      - name: MaritalStatus
        description: "Marital status of customer"
        data_tests:
          - accepted_values:
              values: ['Married', 'Single']
      - name: Gender
        description: "Gender of customer"
        data_tests:
          - accepted_values:
              values: ['Male', 'Female']
      - name: YearlyIncome
        description: "The yearly income of the customer"
      - name: TotalChildren
        description: "The total no. of children of the customer"
      - name: NumberChildrenAtHome
        description: "The total no. of children of the customer"
      - name: EducationLevel
        description: "The highest education obtained by the customer (in English)"
      - name: HouseOwnerFlag
        description: "Indicates whether customer owns a house"
        data_tests:
          - accepted_values:
              values: ['No', 'Yes']
      - name: CarOwnerFlag
        description: "Indicates whether customer owns a car"
        data_tests:
          - accepted_values:
              values: ['No', 'Yes']
      - name: NumberCarsOwned
        description: "The no. of cars owned by the customer"
      - name: DateFirstPurchase
        description: "Date at which first items was purchased by customer (in format yyyy/mm/dd)"
      - name: DaysSinceFirstPurchase
        description: "The no. of days since the first purchase"
      - name: CommuteDistance
        description: "The commute distance to work of the customer"
 


     
      - name: HouseOwnerFlag
        description: "Indicates whether customer owns a house"
        data_tests:
          - accepted_values:
              values: ['Yes', 'No']
      - name: HasChildrenFlag
        description: "Indicates whether customer has children"
        data_tests:
          - accepted_values:
              values: ['Yes', 'No']
      - name: CarOwnerFlag
        description: "Indicates whether customer owns a car"
        data_tests:
          - accepted_values:
              values: ['Yes', 'No']
  
  - name: int_product
    description: "Intermediate view of product, derived from views stg_product, stg_product_category, stg_product_subcategory."
    columns:
      - name: ProductKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: ProductAlternateKey
        description: "The alternate key for this table"
        data_tests:
          - not_null # only satsifies not nullness; alternate keys are not unique
      - name: EnglishProductName
        description: "The name of the product in English"
      - name: EnglishDescription
        description: "The product description in English"
      - name: ModelName
        description: "The name of the model"
      - name: ProductLine
        description: "The product line"
      - name: StandardCost
        description: "The standard cost price of the product"
      - name: Color 
        description: "The color of the product"
      - name: Size 
        description: "The size of the product"
      - name: SizeRange 
        description: "The size range of the product"
      - name: Weight 
        description: "The weight of the product"
      - name: WeightUnitMeasureCode
        description: "The weight unit measure code of the product"
      - name: SizeUnitMeasureCode
        description: "The size unit measure code"
      - name: Class
        description: "The class which the product belongs to"
      - name: Style 
        description: "The style of the product"
      - name: DaysToManufacture
        description: "The no. of days it takes to manufacture the product"
      - name: SafetyStockLevel
        description: "The amount of stock set as safety level for a product"
      - name: ReorderPoint
        description: "The amount of stock at which the product is reordered"
      - name: ListPrice
        description: "The list price of a product"
      - name: DealerPrice
        description: "The dealer pricer of a product"
      - name: FinishedGoodsFlag
        description: "Indicates whether a product is a finished good"
        data_tests:
          - accepted_values:
              values: ["Yes", "No"]
      

          

